@startuml Murder UML
skinparam DefaultFontName Times New Roman

namespace Infrastructure {
    namespace Application {

        class GameService <<application service>> {
            +listJoinedGames(PlayerId): GameId
            +listPublicGames(): []GameId
            +getGame(GameId): Game
            +joinGame(GameId, PlayerId): void
            +leaveGame(GameId, PlayerId): void
            +startGame(GameId): void
            +endGame(GameId): void
            +createGame(string, PlayerId, Visibility, DateTime?): Game
            +deleteGame(GameId): void
        }

        class IdentityService <<application service>> {
            +getIdentity(IdentityId): Identity
            +isUser(IdentityId): bool
            +isGuest(IdentityId): bool
            +createUser(string): IdentityId
            +createGuest(): IdentityId
            +deactivateUser(IdentityId): void
        }

        class AuthenticationService <<application service>> {
            +login(IncomingCredential): CredentialId
            +validate(IncomingCredential): IdentityId
            +revokeCredential(CredentialId): void
            +addMethod(IdentityId, MethodName, IncomingCredential): void
            +removeMethod(IdentityId, MethodName): void
        }

        GameDomain.OwnerId .. IdentityDomain.IdentityId : context mapping

        GameService ..> GameDomain.GameRepository : uses
        GameService ..> GameDomain.PlayerRepository : uses
        GameService ..> GameDomain.GameFactory : delegates creation to
        GameService ..> GameDomain.GameAggregate.Game : returns

        IdentityService ..> IdentityDomain.IdentityRepository : uses
        IdentityService ..> IdentityDomain.User : creates
        IdentityService ..> IdentityDomain.Guest : creates

        AuthenticationService ..> IdentityDomain.Authenticator : delegates to
        AuthenticationService ..> IdentityDomain.CredentialRepository : uses

        namespace GameDomain {
            interface GameRepository <<repository>> {
                +findById(GameId): Game?
                +findByPlayer(PlayerId): GameId[]
                +findPublic(): GameId[]
                +store(Game): void
                +update(Game): void
                +delete(GameId): void
                +exists(GameId): bool
            }

            interface PlayerRepository <<repository>> {
                +findById(PlayerId): Player?
                +findByGame(GameId): Player[]
                +findByOwner(OwnerId): Player?
                +store(Player): void
                +delete(PlayerId): void
                +exists(PlayerId): bool
            }

            class Player <<entity>> {
                +id: PlayerId
                +owner: OwnerId
            }

            class GameAggregate.MurderChain <<value object>> {
                -chain : LinkedList<PlayerId>

                ~killOf(PlayerId) : PlayerId
                ~kill(PLayerId, PlayerId) : PlayerId
                ~leaderboard() : HashMap<PlayerId, int>
                ~participants() : PlayerId[]
            }

            class GameAggregate.Game <<entity, aggregate root>> {
                -murderChain: MurderChain
                +id : GameId
                +name : String
                +visibility: Visibility
                +startTime: DateTime
                +endTime: DateTime?
                +admin: PlayerId

                +killOf(PlayerId) : PlayerId
                +kill(PLayerId, PlayerId) : PlayerId
                +leaderboard() : HashMap<PlayerId, int>
                +participants() : PlayerId[]
            }

            class GameFactory <<factory>> {
                +create(string, []PlayerId, PlayerId, Visibility, DateTime, DateTime?) : Game
            }


            class GameId <<value object>> {
                - id: string
            }

            class PlayerId <<value object>> {
                - id: string
            }

            class OwnerId <<value object>> {
                - id: string
            }

            enum Visibility <<value object>> {
                Public
                Private
            }

            GameAggregate.Game --* GameAggregate.MurderChain : contains
            GameFactory --> GameAggregate.Game : creates
            GameAggregate.Game --* Visibility : contains
            GameAggregate.MurderChain --* PlayerId : contains many
            GameAggregate.Game --* PlayerId : contains
            GameAggregate.Game --* GameId : identified by
            GameRepository --o GameAggregate.Game : stores
            PlayerRepository --o Player : stores
            GameRepository ..> GameId : uses
            GameRepository ..> PlayerId : uses
            PlayerRepository ..> PlayerId : uses
            PlayerRepository ..> GameId : uses
            PlayerRepository ..> OwnerId : uses
            Player --* PlayerId : identified by
            Player --* OwnerId : owned by
        }

        namespace IdentityDomain {
            interface Identity <<entity>> {
                +id : IdentityId
                +name : string
            }

            interface IdentityRepository <<repository>> {
                +identityById(IdentityId) : Identity
                +identityOfName(string) : IdentityId
                +store(Identity) : void
                +update(Identity) : void
                +delete(IdentityId) : void
            }

            interface CredentialRepository <<repository>> {
                +store(IdentityId, CredentialSerializer, StoredCredential): CredentialId
                +findById(CredentialId, CredentialSerializer): (IdentityId, StoredCredential)?
                +findAll(IdentityId, MethodName): CredentialId[]
                +delete(CredentialId): void
                +deleteAll(IdentityId, MethodName): void
                +exists(CredentialId): bool
            }

            class IdentityId <<value object>> {
                -id : string
            }

            class User <<entity>> implements Identity {
                +state : UserState

                construct(string) : User
            }

            class Guest <<entity>> implements Identity {
                construct() : Guest
            }

            enum UserState <<value object>> {
                Active
                Deleted
            }

            interface IncomingCredential <<port>> {
                +methodName : MethodName
            }

            interface StoredCredential <<port>> {
                +methodName : MethodName
            }

            interface CredentialSerializer <<port>> {
                +methodName(): MethodName
                +serialize(StoredCredential): string
                +deserialize(string): StoredCredential
                +prepare(IncomingCredential): StoredCredential
            }

            class MethodName <<value object>> {
                +type: string
            }

            class CredentialId <<value object>> {
                -id: string
            }

            interface AuthenticationMethod <<port>> {
                +methodName : MethodName
                +serializer(): CredentialSerializer
                +resolve(IncomingCredential): IdentityId?
                +verify(IncomingCredential): bool
            }

            class Authenticator <<domain service>> {
                -methods : HashMap<MethodName, AuthenticationMethod>
                -credentialsRepo : CredentialRepository
                +authenticate(IncomingCredential): IdentityId
            }

            User --* UserState : contains
            IdentityRepository --o Identity : stores
            Identity --* IdentityId : identified by
            IdentityRepository ..> IdentityId : uses

            Authenticator --o AuthenticationMethod : delegates to
            AuthenticationMethod ..> IncomingCredential : receives
            AuthenticationMethod ..> StoredCredential : verifies against
            AuthenticationMethod ..> IdentityId : resolves
            AuthenticationMethod --* MethodName : contains
            AuthenticationMethod --> CredentialSerializer : provides
            CredentialSerializer ..> StoredCredential : serializes
            CredentialSerializer ..> IncomingCredential : prepares from
            CredentialRepository ..> CredentialSerializer : uses
            CredentialRepository ..> CredentialId : uses
            CredentialRepository ..> IdentityId : uses
            CredentialRepository ..> MethodName : uses
            CredentialRepository ..> StoredCredential : uses
            StoredCredential --* MethodName : contains
            IncomingCredential --* MethodName : contains
        }
    }

}

@enduml