@startuml Murder UML
skinparam DefaultFontName Times New Roman

namespace Infrastructure {
    namespace Application {

        class GameService <<usecase>> {
            +listJoinedGames(PlayerId): GameId
            +listPublicGames(): []GameId
            +getGame(GameId): Game
            +joinGame(GameId, PlayerId): void
            +leaveGame(GameId, PlayerId): void
            +startGame(GameId): void
            +endGame(GameId): void
            +createGame(string, PlayerId, Visibility, DateTime?): Game
            +deleteGame(GameId): void
        }

        class IdentityService <<usecase>> {
            +getIdentity(IdentityId): Identity
            +isUser(IdentityId): bool
            +isGuest(IdentityId): bool
            +createUser(string): IdentityId
            +createGuest(): IdentityId
            +deactivateUser(IdentityId): void
        }

        class AuthenticationService <<usecase>> {
            +login(MethodName, IncomingCredential): SessionToken
            +logout(SessionToken): void
            +validate(SessionToken): IdentityId
            +addMethod(IdentityId, MethodName, IncomingCredential): void
            +removeMethod(IdentityId, MethodName): void
        }

        GameDomain.OwnerId .. IdentityDomain.IdentityId : context mapping

        namespace GameDomain {
            interface GameRepository <<repository>> {
            }

            interface PlayerRepository <<repository>> {
            }

            class Player <<entity>> {
                +id: PlayerId
                +owner: OwnerId
            }

            class GameAggregate.MurderChain <<value object>> {
                -chain : LinkedList<PlayerId>

                ~killOf(PlayerId) : PlayerId
                ~kill(PLayerId, PlayerId) : PlayerId
                ~leaderboard() : HashMap<PlayerId, int>
                ~participants() : PlayerId[]
            }

            class GameAggregate.Game <<entity, aggregate root>> {
                -murderChain: MurderChain
                +id : GameId
                +name : String
                +visibility: Visibility
                +startTime: DateTime
                +endTime: DateTime?
                +admin: PlayerId

                +killOf(PlayerId) : PlayerId
                +kill(PLayerId, PlayerId) : PlayerId
                +leaderboard() : HashMap<PlayerId, int>
                +participants() : PlayerId[]
            }

            class GameFactory <<factory>> {
                +create(string, []PlayerId, PlayerId, Visibility, DateTime, DateTime?) : Game
            }


            class GameId <<value object>> {
                - id: string
            }

            class PlayerId <<value object>> {
                - id: string
            }

            class OwnerId <<value object>> {
                - id: string
            }

            enum Visibility <<value object>> {
                Public
                Private
            }

            GameAggregate.Game --* GameAggregate.MurderChain : contains
            GameFactory --> GameAggregate.Game : creates
            GameAggregate.Game --* Visibility : contains
            GameAggregate.MurderChain --* PlayerId : contains many
            GameAggregate.Game --* PlayerId : contains
            GameAggregate.Game --* GameId : identified by
            GameRepository --o GameAggregate.Game : stores
            PlayerRepository --o Player : stores
            GameRepository ..> GameId : uses
            GameRepository ..> PlayerId : uses
            PlayerRepository ..> PlayerId : uses
            PlayerRepository ..> GameId : uses
            Player --* PlayerId : identified by
            Player --* OwnerId : owned by
        }

        namespace IdentityDomain {
            interface Identity <<entity>> {
                +id : IdentityId
                +name : string
            }

            interface IdentityRepository <<repository>> {
            }

            interface CredentialRepository <<repository>> {
                +store(IdentityId, CredentialSerializer, StoredCredential): void
                +find(IdentityId, MethodName, CredentialSerializer): StoredCredential?
                +findMethods(IdentityId): MethodName[]
                +delete(IdentityId, MethodName): void
                +exists(IdentityId, MethodName): bool
            }

            class IdentityId <<value object>> {
                -id : string
            }

            class User <<entity>> implements Identity {
                +state : UserState

                construct(string) : User
            }

            class Guest <<entity>> implements Identity {
                construct() : Guest
            }

            enum UserState <<value object>> {
                Active
                Deleted
            }

            interface IncomingCredential <<port>> {
                +methodName : MethodName
            }

            interface StoredCredential <<port>> {
                +methodName : MethodName
            }

            interface CredentialSerializer <<port>> {
                +methodName(): MethodName
                +serialize(StoredCredential): string
                +deserialize(string): StoredCredential
                +prepare(IncomingCredential): StoredCredential
            }

            class MethodName <<value object>> {
                +type: string
            }

            interface AuthenticationMethod <<port>> {
                +methodName : MethodName
                +serializer(): CredentialSerializer
                +resolve(IncomingCredential): IdentityId?
                +verify(IncomingCredential): bool
            }

            class Authenticator <<domain service>> {
                -methods : HashMap<MethodName, AuthenticationMethod>
                -credentialsRepo : CredentialRepository
                +authenticate(IncomingCredential): IdentityId
            }

            User --* UserState : contains
            IdentityRepository --> Identity : stores
            Identity --* IdentityId : identified by
            IdentityRepository --> IdentityId : uses

            Authenticator --* AuthenticationMethod : delegates to
            AuthenticationMethod ..> IncomingCredential : receives
            AuthenticationMethod ..> StoredCredential : verifies against
            AuthenticationMethod ..> IdentityId : resolves
            AuthenticationMethod --> CredentialSerializer : provides
            CredentialSerializer ..> StoredCredential : serializes
            CredentialSerializer ..> IncomingCredential : prepares from
            CredentialRepository ..> CredentialSerializer : uses
            CredentialRepository ..> IdentityId : uses
            CredentialRepository ..> MethodName : uses
            CredentialRepository ..> StoredCredential : stores
        }
    }

}

@enduml